#!/usr/bin/env python3
"""
Self-host Google Fonts to remove the render-blocking third-party CSS request.

Downloads the woff2 files for the latin subset of Hurricane / Lato / Lora,
rewrites the CSS to point at local /fonts/ paths, and writes:
  public/fonts/fonts.css
  public/fonts/*.woff2

Re-run when the font families or weights change.
"""
import re
import urllib.request
from pathlib import Path

OUT = Path('/tmp/hk/public/fonts')
OUT.mkdir(parents=True, exist_ok=True)

UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
CSS_URL = ('https://fonts.googleapis.com/css2?family=Hurricane&'
           'family=Lato:wght@300;400;700;900&family=Lora:wght@400;500;600;700&display=swap')

req = urllib.request.Request(CSS_URL, headers={'User-Agent': UA})
css = urllib.request.urlopen(req, timeout=30).read().decode()

# Split into @font-face blocks and keep only the 'latin' subset. The site's copy
# is ASCII; latin-ext, cyrillic, greek, and vietnamese blocks are dead weight.
blocks = re.findall(r'/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]+\})', css)
keep_subsets = {'latin'}
kept = [(name, block) for name, block in blocks if name in keep_subsets]

out_css = ['/* Self-hosted fonts - generated by scripts/fetch-fonts.py */']
count = 0
for name, block in kept:
    m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block)
    if not m:
        continue
    url = m.group(1)
    fname = url.rsplit('/', 1)[-1]
    dest = OUT / fname
    if not dest.exists():
        data = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA}), timeout=30).read()
        dest.write_bytes(data)
    block = block.replace(m.group(0), f'url(/fonts/{fname})')
    out_css.append(block)
    count += 1

(OUT / 'fonts.css').write_text('\n'.join(out_css) + '\n')
print(f'{count} @font-face blocks, {len(list(OUT.glob("*.woff2")))} woff2 files')
print(f'css: {(OUT/"fonts.css").stat().st_size} bytes | total woff2: {sum(p.stat().st_size for p in OUT.glob("*.woff2"))/1024:.0f} KB')
